defaults: 
  - multilabel_mix.yaml
  - background_noise.yaml
  - gain.yaml
  - pitch_shift.yaml
  - colored_noise.yaml
  # - polarity_inversion.yaml

# waveform_augmentations: 
#   ColoredNoise:
#     _target_: torch_audiomentations.AddColoredNoise
#     p: 0.5
#     min_snr_in_db: 3.0 
#     max_snr_in_db: 30.0
#     min_f_decay: -2.0
#     max_f_decay: 2.0
#   PitchShift:
#     _target_: torch_audiomentations.PitchShift
#     p: 0.5
#     sample_rate: ${datamodule.dataset.feature_extractor.sampling_rate}
#     min_transpose_semitones: -4
#     max_transpose_semitones: 4
#   Gain:
#     _target_: torch_audiomentations.Gain
#     p: 0.5
#     min_gain_in_db: -15.0
#     max_gain_in_db: 5.0
#   PolarityInversion:
#     _target_: torch_audiomentations.PolarityInversion
#     p: 0.3
  
 
  
  
  
  # colored_noise:
  #   p: 0.5
  #   min_snr_in_db: 3.0 
  #   max_snr_in_db: 30.0
  #   min_f_decay: -2.0
  #   max_f_decay: 2.0
    #background_noise:
    #    background_paths: "/mnt/home/rheinrich/deep_bird_detect/datapipeline/speech_command_dataset"
    #    prob: 0.5
    #    min_snr_in_db: 3.0
    #    max_snr_in_db: 30.0

# spectrogram_augmentations:
#     time_masking:
#       time_mask_param: 100
#       prob: 0.5
#     frequency_masking:
#       freq_mask_param: 100
#       prob: 0.5
#     time_stretch:
#       prob: 0.5
#       min_rate: 0.8
#       max_rate: 1.2