normalize: True
mean: -4.268 # Mean of log-scaled Mel spectrograms from AuioSet
std: 4.569 # Standard deviation of log-scaled Mel spectrograms from AuioSet
use_spectrogram: True
n_fft: 1024
hop_length: 79
n_mels: 128
db_scale: True
target_height: null
target_width: 1024