resizer:
  _target_: birdset.datamodule.components.resize.Resizer
  db_scale: True # manually adjusted!! False when not using it
  target_height: null
  # target_width: null  # für das Training von Efficientnet
  target_width: 1024  # für das Training von ast
