from . import wav2vec2
from . import hubert
from . import ast 
from . import perch
from . import efficientnet
from . import convnext
from . import mobilenet
from . import resnet
#from ..base_module import *