model_name: "BirdNet-v2.4"
model:
  _target_: src.modules.models.logistic_regression.DeterministicLogisticRegression
  embedding_size: 1024
  num_classes: ${datamodule.dataset.n_classes}

model_type: embedding
sampling_rate: 48_000
# window_size_s: 3.0
# hop_size_s: 3.0
torch_compile: False