model_name: "Deterministic Logistic Regression Perch"
model:
  _target_: src.modules.models.logistic_regression.DeterministicLogisticRegression
  embedding_size: 1280
  num_classes: ${datamodule.dataset.n_classes}

model_type: embedding
sampling_rate: 32_000
window_size_s: 5.0
hop_size_s: 5.0