model: 
  _target_: birdset.modules.models.perch.PerchModel
  num_classes: ${datamodule.dataset.n_classes}
  tfhub_version: 4
  train_classifier: False
  restrict_logits: True
  label_path: ${paths.root_dir}/resources/perch/label_updated.csv
  task: ${module.task}
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null

model_name: perch
model_type: waveform
torch_compile: False
sampling_rate: 32_000
normalize_spectrogram: False
normalize_waveform: "instance_peak_normalization"