model:
  _target_: src.modules.models.resnet.ResNetClassifier
  baseline_architecture: 'resnet18'
  num_classes: 21
  num_channels: 1
  pretrained: True

model_name: resnet18
model_type: vision
torch_compile: False
sampling_rate: 32_000
normalize_waveform: null
normalize_spectrogram: True