_target_: src.datamodule.gadme_datamodule.GADMEDataModule

defaults:
  - _self_
  - transforms: bird_default.yaml
  - extractors: default_aug.yaml
  - loaders: default.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: bird_db
  hf_path: DBD-research-group/gadme_v1
  hf_name: bird_db
  seed: ${seed}
  n_classes: 5
  n_workers: 3
  column_list: ["input_values", "ebird_code", "ebird_code_multiclass"]
  val_split: 0.2
  task: ${module.task}
  classlimit: 500
  eventlimit: 5




