#NES
_target_: src.datamodule.gadme_datamodule.GADMEDataModule

defaults:
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml


dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: columbia_costs_rica
  hf_path: DBD-research-group/gadme_v1
  hf_name: columbia_costs_rica
  seed: ${seed}
  n_classes: 90
  n_workers: 3
  val_split: 0.2
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}
  classlimit: 500
  eventlimit: 5



