_target_: dataset.embeddings.embedding_backend_model.BirdNet

model_key: "birdnet"
model_name: "BirdNet-v2.4"
num_classes: ${datamodule.dataset.n_classes}
embed_dim: 1024

config:
  window_size_s: 3.0
  hop_size_s: 3.0
  sample_rate: 48_000
  model_path: ${paths.model_path}/BirdNet/V2.4/BirdNET_GLOBAL_6K_V2.4_Model_FP32.tflite
  num_tflite_threads: 4
  class_list_name: "birdnet_v2_4"

# the model's tflite file has to be downloaded.
# it is available @ github: https://github.com/kahst/BirdNET-Analyzer
# https://github.com/kahst/BirdNET-Analyzer/tree/main/checkpoints/V2.4