_target_: dataset.embeddings.embedding_backend_model.Perch

model_key: "taxonomy_model_tf"
model_name: "GooglePerch-V4"
num_classes: ${datamodule.dataset.n_classes}
embed_dim: 1280
config:
  window_size_s: 5.0
  sample_rate: 32_000
  hop_size_s: 5.0
  model_path: ""
  tfhub_version: 4
