_target_: dataset.embeddings.embedding_backend_model.Perch

model_key: "taxonomy_model_tf"
model_name: "GooglePerch-V4"
num_classes: ${datamodule.dataset.n_classes}
embed_dim: 1280
config:
  window_size_s: 5.0
  sample_rate: 32_000
  hop_size_s: 5.0
  model_path: ${paths.model_path}/Perch
  tfhub_version: null

# You can either specify the version @ tfhub
# currently 1/2/3/4 
# or specify the path to the downloaded archive.
# Perch is available here:
# https://www.kaggle.com/models/google/bird-vocalization-classifier/frameworks/TensorFlow2/variations/bird-vocalization-classifier