#NES colombia costa rica
_target_: src.datamodule.gadme_datamodule.GADMEDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: NES
  hf_path: DBD-research-group/gadme
  hf_name: NES
  seed: ${seed}
  n_classes: 89
  n_workers: 3
  val_split: 0.2
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}
  class_weights_loss: null
  class_weights_sampler: null
  classlimit: 500
  eventlimit: 5