_target_: src.utils.path_utils.LocalDsManager
data_dir: ${paths.dataset_path}/embeddings/${embedding_module.embedding.model_name}
dataset_name: ${datamodule.dataset.dataset_name}
hf_path: DBD-research-group/gadme_v1
hf_name: ${datamodule.dataset.hf_name}
num_proc: 3